# Generated by Django 3.1.3 on 2020-11-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue', '0002_auto_20201124_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poulet',
            name='poids',
            field=models.FloatField(null=True, verbose_name='poids'),
        ),
    ]
