# Generated by Django 3.1.3 on 2020-11-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue', '0003_auto_20201125_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poulet',
            name='poids',
            field=models.FloatField(blank=True, null=True, verbose_name='poids'),
        ),
    ]
